// <auto-generated />
namespace Appa_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class SupplierPriceLineItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SupplierPriceLineItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201802091118327_SupplierPriceLineItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
